### ISSUE TITLE
call to private DoRender method ?

### ISSUE THREAD

**Issue by tothpaul** [eugeneloza/Mazer#2]
Hello,

I can't compile the project because in Mazer.pas do_timer() calls the private member  window.DoRender; 

player.FallingEffect:=false; is unknown also.

This with castle_game_engine-5.2.0-src.zip

event after an SVN checkout from 
http://svn.code.sf.net/p/castle-engine/code/trunk/castle_game_engine

Regards

**Comment by eugeneloza** [comment]
@tothpaul , hi!
Thanks for your interest!

I'm using latest GIT of the CGE (just checked with yesterday-version). And yes, the engine API changed a little since 5.2.0.

Yes, player.fallingeffect was added in GIT in ~December 2015. You can just comment it out - it fixes camera tilt while moving downstairs and not critical. Alternatively you can set player.camera.fallingeffect:=false at each Update procedure (practically this is what player.fallingeffect does).

About window.DoRender I'm not exactly sure. It works fine for me in GIT engine version. You can safely replace it with if "loadscreen_IMG<>nil then loadscreen_IMG.ImageChanged;" It's more efficient as it lets the Engine handle render on its own and I'll update the code as soon as possible (right now I'm working on interface of the game).
And I'll also need to update readme_compile.txt.

Feel free to ask if you'll need any further help or explanation.

**Comment by tothpaul** [comment]
great ! now it works perfectly (Windows 8 64bits)

good job :+1:

**Comment by eugeneloza** [comment]
Thanks for feedback! I'll fix/extend the readme on Git soon (maybe, tomorrow).

**Comment by eugeneloza** [comment]
fixed by https://github.com/eugeneloza/Mazer/commit/06bbda04052a6df0700cad786afde0950176c1f4 and https://github.com/eugeneloza/Mazer/commit/df2330a744c68a5096b77a08be4346d706d2d3be
